name: Sync Jobcy Portal

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  sync-jobcy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout DevOps Website
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Clone Jobcy Portal
      run: |
        git clone https://github.com/Karthik2340/jobcy-job-portal.git jobcy-temp
        cd jobcy-temp
        git checkout main
        
    - name: Sync Jobcy Files
      run: |
        # Copy Jobcy frontend files to DevOps website
        cp -r jobcy-temp/jobcy-frontend-main/src/app/* src/app/jobcy/
        
        # Update API endpoints to use Jobcy backend
        find src/app/jobcy -name "*.tsx" -o -name "*.ts" | xargs sed -i 's|process.env.NEXT_PUBLIC_API_URL|"https://jobcy-job-portal.vercel.app/api"|g'
        
    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "🔄 Auto-sync: Update Jobcy portal from main repo" || exit 0
        git push
